name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read
  id-token: write
  packages: write
  security-events: write

jobs:
  build:
    permissions:
      contents: read
      id-token: write
      packages: write
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: Build docker
        uses: meysam81/build-docker@main
        with:
          cosign: true
          image-name: ghcr.io/${{ github.repository }}
          image-extra-tags: |
            ghcr.io/${{ github.repository }}:${{ github.run_id }}
            ghcr.io/${{ github.repository }}:latest
          kubescape: true
          platforms: linux/amd64
